<?php


namespace Bridge\Intervention\Image;


class ImageManager extends \Intervention\Image\ImageManager
{
    public static function fromImagick(): self
    {
        return new static(array('driver' => 'imagick'));
    }

    public static function fromGd(): self
    {
        return new static(array('driver' => 'gd'));
    }

    public function make($data)
    {
        return parent ::make($data); // TODO: Change the autogenerated stub
    }
}