<?php

declare(strict_types=1);

namespace Bridge\Laminas\Authentication;


use Laminas\Authentication\Adapter;

class AuthenticationService extends \Laminas\Authentication\AuthenticationService
{
    public function authenticate(Adapter\AdapterInterface $adapter = null):Result
    {
        return parent ::authenticate($adapter); // TODO: Change the autogenerated stub
    }
}