<?php


namespace Bridge\Aws\Ses;


class SesClient extends \Aws\Ses\SesClient
{
    protected string $source;
    protected string $subject;
    protected string $htmlBody;
    protected array $toAddresses = [];

    public function sendEmail(array $args = []): \Aws\Result
    {
        $parameters = [
            'Source' => $this -> source,
            'Message' => [
                'Subject' => ['Data' => $this -> subject],
                'Body' => [
                    'Html' => [
                        'Data' => $this -> htmlBody
                    ]
                ]
            ]
        ];
        $parameters['Destination']['ToAddresses'] = $this -> toAddresses;
        $args = array_merge($args, $parameters);
        return parent ::sendEmail($args); // TODO: Change the autogenerated stub
    }

    public function addToAddress(string $toAddress): void
    {
        $this -> toAddresses[] = $toAddress;
    }

    public function setHtmlBody(string $htmlBody): void
    {
        $this -> htmlBody = $htmlBody;
    }

    public function setSubject(string $subject): void
    {
        $this -> subject = $subject;
    }


    public function setSource(string $source): void
    {
        $this -> source = $source;
    }

}